services:
  shard1:
    build: ./shard1
    image: shard1
    ports:
      - "5001:5001"
  
  shard2:
    build: ./shard2
    image: shard2
    ports:
      - "5002:5002"

  shard3:
    build: ./shard3
    image: shard3
    ports:
      - "5003:5003"
  
  shard4:
    build: ./shard4
    image: shard4
    ports:
      - "5004:5004"
    
  aggregator:
    build: ./aggregator
    image: aggregator
    ports:
      - "8080:8080"
    depends_on:
      - shard1
      - shard2
      - shard3